name       : vala
version    : 0.44.7
release    : 35
source     :
    - https://download.gnome.org/sources/vala/0.44/vala-0.44.7.tar.xz : bf1ff4f59d5de2d626e98e98ef81cb75dc1e6a27610a7de4133597c430f1bd7c
homepage   : https://live.gnome.org/Vala
component  :
    - programming
    - ^libvala : programming.library
    - ^libvala-devel : programming.devel
    - ^vala-docs : programming.docs
    - ^valadoc : programming.tools
    - ^valadoc-devel : programming.devel
license    :
    - GPL-2.0
    - LGPL-2.1
summary    :
    - Vala is a new programming language that aims to bring modern programming language features to GNOME developers without imposing any additional runtime requirements and without using a different ABI compared to applications and libraries written in C.
    - ^libvala : Vala libraries
    - ^libvala-devel : Vala development files
    - ^vala-docs : Documentation for Vala
    - ^valadoc : Vala Documentation Tool
    - ^valadoc-devel : Valadoc development files
description:
    - Vala is a new programming language that aims to bring modern programming language features to GNOME developers without imposing any additional runtime requirements and without using a different ABI compared to applications and libraries written in C.
    - ^libvala : Vala libraries
    - ^libvala-devel : Vala development files
    - ^vala-docs : Documentation for Vala
    - ^valadoc : Vala Documentation Tool
    - ^valadoc-devel : Valadoc development files
patterns   :
    - ^libvala :
        - /usr/lib64/libvala-*.so.*
    - ^libvala-devel :
        - /usr/include
        - /usr/lib64/libvala-*.so
        - /usr/lib64/pkgconfig
        - /usr/share/pkgconfig
        - /usr/share/aclocal
    - ^vala-docs :
        - /usr/share/doc
        - /usr/share/devhelp
    - ^valadoc :
        - /usr/bin/valadoc*
        - /usr/lib64/valadoc
        - /usr/lib64/libvaladoc*.so.*
        - /usr/share/man/man1/valadoc*
        - /usr/share/valadoc
    - ^valadoc-devel :
        - /usr/include/valadoc-*
        - /usr/lib64/libvaladoc*.so
        - /usr/lib64/pkgconfig/valadoc-*.pc
        - /usr/share/vala/vapi/valadoc*
    - /usr/lib64/vala-*
    - /usr/share/vala
    - /usr/share/vala-*
    - /usr/share/man/vala*
builddeps  :
    - pkgconfig(libgvc)
rundeps    :
    - libvala-devel
    - ^vala-docs : vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
