name       : vala
version    : 0.56.7
release    : 67
source     :
    - https://download.gnome.org/sources/vala/0.56/vala-0.56.7.tar.xz : 3d39c7596d5fa9ae8bfeae476669f811f7057b7f7b9308478a27b68443d8b003
homepage   : https://wiki.gnome.org/Projects/Vala
component  :
    - programming
    - ^libvala : programming.library
    - ^libvala-devel : programming.devel
    - ^vala-docs : programming.docs
    - ^valadoc : programming.tools
    - ^valadoc-devel : programming.devel
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
summary    :
    - Vala is a programming language using modern high level abstractions without imposing additional runtime requirements and without using a different ABI compared to applications and libraries written in C.
    - ^libvala : Vala libraries
    - ^libvala-devel : Vala development files
    - ^vala-docs : Documentation for Vala
    - ^valadoc : Vala Documentation Tool
    - ^valadoc-devel : Valadoc development files
description:
    - Vala is a programming language using modern high level abstractions without imposing additional runtime requirements and without using a different ABI compared to applications and libraries written in C.
    - ^libvala : Vala libraries
    - ^libvala-devel : Vala development files
    - ^vala-docs : Documentation for Vala
    - ^valadoc : Vala Documentation Tool
    - ^valadoc-devel : Valadoc development files
patterns   :
    - ^libvala :
        - /usr/lib64/libvala-*.so.*
    - ^libvala-devel :
        - /usr/include
        - /usr/lib64/libvala-*.so
        - /usr/lib64/pkgconfig
        - /usr/share/pkgconfig
        - /usr/share/aclocal
    - ^vala-docs :
        - /usr/share/doc
        - /usr/share/devhelp
    - ^valadoc :
        - /usr/bin/valadoc*
        - /usr/lib64/valadoc-*
        - /usr/lib64/libvaladoc*.so.*
        - /usr/share/man/man1/valadoc*
        - /usr/share/valadoc*
    - ^valadoc-devel :
        - /usr/include/valadoc-*
        - /usr/lib64/libvaladoc*.so
        - /usr/lib64/pkgconfig/valadoc-*.pc
        - /usr/share/vala/vapi/valadoc*
    - /usr/lib64/vala-*
    - /usr/share/vala
    - /usr/share/vala-*
    - /usr/share/man/vala*
builddeps  :
    - pkgconfig(libgvc)
    - help2man
rundeps    :
    - libvala-devel
    - ^vala-docs : vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
